Adding conv1d and conv3d
BindsNET/bindsnet pull request #526
Opened 2021-11-23 23:41 UTC by hafezgh

The conv1d and conv3d classes and their corresponding learning methods are added.

2021-12-02 20:54 UTC, Hananel-Hazan requested changes

2021-12-02 20:54 UTC, Hananel-Hazan commented on test/network/test_conv1d.py
> +
This code should be at MNIST examples. 
Test directory contain tests scripts that perform a integrity check for the models.

2021-12-02 20:54 UTC, Hananel-Hazan commented on test/network/test_conv3d.py
> +### for each image (each sample has size (28, 28, 28))
This code should be at MNIST examples. 
Test directory contain tests scripts that perform a integrity check for the models.

2021-12-03 02:40 UTC, hafezgh commented
I relocated the files.

2021-12-16 23:56 UTC, Hananel-Hazan commented
Thank you Hafez for the great work !

2021-12-16 23:56 UTC, Hananel-Hazan approved these changes

2021-12-16 23:56 UTC, merged